# .github/workflows/android-ci.yml

name: Android CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/dists
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 第 5 步: 解码 Keystore 文件 (修正 if 条件语法)
      - name: Decode Keystore
        # 修正: 使用 ${{ }} 包裹整个表达式
        if: ${{ secrets.RELEASE_KEYSTORE_BASE64 != '' }}
        run: |
          echo "Decoding keystore..."
          mkdir -p $GITHUB_WORKSPACE/app
          echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 --decode > $GITHUB_WORKSPACE/app/release.jks
          echo "Keystore decoded."


      # --- 新增调试步骤 --- (修正 if 条件语法)
      - name: Verify Keystore File Existence
        # 修正: 使用 ${{ }} 包裹整个表达式
        if: ${{ secrets.RELEASE_KEYSTORE_BASE64 != '' }}
        run: |
          echo "Checking for keystore file at $GITHUB_WORKSPACE/app/release.jks"
          ls -l $GITHUB_WORKSPACE/app/release.jks || echo "Keystore file not found!"

      # 第 6 步: 使用 Gradle 构建 Release AAB (无需 if 条件，保持不变)
      - name: Build Release AAB with Gradle
        env:
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
          RELEASE_KEYSTORE_PATH: "${{ github.workspace }}/app/release.jks"
        run: ./gradlew bundleRelease

      # 第 7 步: 上传 Release AAB (保持不变)
      - name: Upload Release AAB
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: app/build/outputs/bundle/release/*.aab